/*
 * This file was generated by the mkbuiltins program.
 */

#include <sys/cdefs.h>
#define BLTINCMD 0
#define BREAKCMD 1
#define CDCMD 2
#define DOTCMD 3
#define ECHOCMD 4
#define EVALCMD 5
#define EXECCMD 6
#define EXITCMD 7
#define EXPORTCMD 8
#define EXPRCMD 9
#define GETOPTSCMD 10
#define HASHCMD 11
#define JOBIDCMD 12
#define JOBSCMD 13
#define LOCALCMD 14
#define PWDCMD 15
#define READCMD 16
#define RETURNCMD 17
#define SETCMD 18
#define SETVARCMD 19
#define SHIFTCMD 20
#define TRAPCMD 21
#define TRUECMD 22
#define UMASKCMD 23
#define UNSETCMD 24
#define WAITCMD 25

struct builtincmd {
      char *name;
      int code;
};

extern int (*const builtinfunc[])();
extern const struct builtincmd builtincmd[];
