/*
 * This file was generated by the mksignames program.
 */

#include "shell.h"

char *const sigmesg[32] = {
      0,
      "Hangup",
      "Interrupt",
      "Quit",
      "Illegal instruction",
      "Trace/BPT trap",
      "abort",
      "Bus error",
      "Floating exception",
      "Killed",
      "User signal 1",
      "Memory fault",
      "User signal 2",
      "Broken pipe",
      "Alarm call",
      "Terminated",
      0,
      0,
      0,
      "Stopped",
      "Stopped",
      "Stopped (input)",
      "Stopped (output)",
      0,
      "Time limit exceeded",
      0,
      0,
      "Profiling alarm",
      0,
      0,
      "Power fail",
      "Bad system call",
};
