#ifndef _ARM_CPU_H
#define _ARM_CPU_H

#define RESET_EXCEPTION			0
#define UNDEFINED_INSTRUCTION_EXCEPTION	1
#define	SUPERVISOR_CALL_EXCEPTION	2
#define	PREFETCH_ABORT_EXCEPTION	3
#define	DATA_ABORT_EXCEPTION		4
#define	IRQ_EXCEPTION			5
#define	FAST_IRQ_EXCEPTION		6

#define SPSR_MASK_ARM_STATE		0x01000020U
#define SPSR_MASK_THUMB_STATE		0x00000020U
#define SPSR_MASK_JAZELLE_STATE		0x01000000U

#endif  /* _ARM_CPU_H */
